run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt:*
      - github.com/spf13/cobra.*
      - github.com/spf13/viper.*
      - github.com/spf13/pflag.*
