version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ripkitten-co/filehound/internal/version.Version={{.Version}}
    binary: filehound

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: ripkitten-co
    name: filehound
  draft: false
  prerelease: auto

brews:
  - name: filehound
    repository:
      owner: ripkitten-co
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/ripkitten-co/filehound"
    description: "Blazing fast file hunter CLI"
    test: |
      system "#{bin}/filehound version"
